
import { notoSans } from '../config/fonts';
import "./globals.css";
import type { Metadata } from "next";
import { Providers } from "./providers";
import { ReactNode } from 'react'
import { Lang } from '@/i18n/settings';
import { AuthErrorHandler } from '@/features/errors/error-handler-content';

export const metadata: Metadata = {
  title: "Zonaraíz",
  description: "Generated by Zonaraíz",
};

export function generateStaticParams() {
  return [
    { lang: "es" },
    { lang: "en" },
  ]
}

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: ReactNode;
  params: Promise<{ lang: string }>
}>) {
  const { lang: langParam } = await params;
  const lang = langParam as Lang;

  return (
    <html
      lang={lang}
      suppressHydrationWarning
    >
      <body
        className={`${notoSans.variable} antialiased`}
      >
        <Providers>
          <AuthErrorHandler />
          <main className="min-h-screen bg-background mx-auto">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
